#pragma once

#define CPP_CMAKE_TEMPLATE_VERSION "0.0.0"

#define CPP_CMAKE_TEMPLATE_MAJOR_VERSION 0
#define CPP_CMAKE_TEMPLATE_MINOR_VERSION 0
#define CPP_CMAKE_TEMPLATE_PATCH_VERSION 0
#define CPP_CMAKE_TEMPLATE_TWEAK_VERSION "224574d"
